{% set name = "pyplis" %}
{% set version = "1.5.0rc1" %}
{% set python_min = "3.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64497a6f58c2cdd2faf39ed8bf0a4fa2e6ff1bf50de0bdca833d4463fda2876f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - setuptools
    - numpy     
    - scipy 
    - pandas
    - astropy-base
    - matplotlib-base
    - basemap
    - opencv
    - geonum >=1.6
    - pydoas >=2.0.3
    - pyproj
    - progressbar

test:
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - python -c "import pyplis; print(pyplis.__version__)"

about:
  home: https://github.com/jgliss/pyplis
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Python library for the analysis UV SO2 camera data
  doc_url: https://pyplis.readthedocs.io/
  dev_url: https://github.com/jgliss/pyplis

extra:
  recipe-maintainers:
    - jgliss
