travis:
  secure:
    BINSTAR_TOKEN: cjgRZRT9S8zzuu367iBdmGhXu9kLQwx4zzBoX7SlSsXcYqsDi5WRp/AOfLW25enhEpMCViI5rUfsfYukPz4msZa8jQadZNlYfme/654QxxL+S8LOw3U+O9Ipnfv8ZcPK7vBGNvI1FKZCcG33FU/ST7iQnEvYsyg5jGein6vCQX0Pf1e5JF4Y2h9msgqgvrQmGol23VodQSiUxyAK1jlrBTy1s4hndomFDZ5zaMBcpJ+GS0hHBm8U5IgVYQvcPsuTm+FITWDVyPrHJ6xuRopUmZCiRw2fTV4o1LYQggzSas9hVuSjMxwCnPu7DQ/FbIeIdRFokvehcpnxxlObzgHiM1Z8NjHArG9h7kbNfIKD5vxKae1uodCCGn+FxRb2rALFqaC1fqbgX7YJVA1n0MkO4iowBoaaMp1NuVyIw5qMV1Xw+2OwfP04031vsr40Tgs+HcEBG++WVtaHsQtz3nUd+nO9RizrVDmvWl/waiC6IStnEebS3nwks+g8v8VNoD2gEYAAJ0MJU7KKv78PAKDUpAmH09XYTCV9ajX8oS3wPb93r7eUJlln1zZTT0NEHKFe+jwU9F4NvHJ2PNrDYxbLHlQX066/ydOt67mLSl/ECa7EZjC8EQNQMI4UtmHIa9LIx26CKYoKObDnyyp/ZgVPmiRJOr/l7+d0ieTE/xdcYus=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
