travis:
  secure:
    BINSTAR_TOKEN: awXTT9Kq8uWCI7xEmn6eNkNhXExrHGE3Tf5MP1M1yLWq3mK5aMEKGzxUmORZer/wnO5rggEH8L7Q3+r1vAYx7HVgXP6Q8KwRORa05HvA7GQ1/lUPMKLFjV8HLobF+lMYQkBFwQJzjvEbZ/Wuh9cBuhJWrtCPf1a3f9Nb7vNPfohJzLTf1AUzg/p3gMBiNjL3wVsHw0XbbMKo1FfBIDlVLHWnKUs8zq5MX2xh84F1n9BGy2DhRwJry/jITCgA7oeSmXht+XzSqDT0PQ/0ZEEXLgqdoXjE5ufSOoGN5I0XA0NP7+LZb+wT27F9WC2/ABWFIrXXy/DiytqfbgdrElm139UiT7wM9Ea+hWf1FLi1Vy/E5+2mqpJfE3ajctMcm8DYMJHr7mWuSqvwbf7a1SyfRVK6KaVj75E6c/vrewUD9lQTUFB69XlJui6DeSlfkuGK8yITDNgJB5EPiq5kXKerZd/2EODZZgXMef5ZduMEnRg3vs0f/hb6fgaxkvHZFxlv3PX9/dPVd3nn0ssVzBcvkzFkiiR70bZ78D5zz3JOKrKcj00W1DO9ecBp8CJaQ4h7ShT+Dsgaiffh+Xxc3OOVKm9qMTJLC0eKM3V5GnWXanqZaxyFS3Zo/qXvBDhLWoIWwfXtEgPFtGPBLMO3m0+tRIxRobE4TN7hufrArwna4s4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
